### PR TITLE
move beast_data.py to the BEAST repo

### PR DESCRIPTION
**Pull request by lea-hagen**
The BEAST needs the functions that were in `beast_data.py` to read in the noise/SED/lnP files, so I've moved it there.  This PR deletes `beast_data.py`, and in the places where it was used (`megabeast.py` and `plot_import_data.py`), imports `beast.tools.read_beast_data` instead.

This should not be merged until BEAST-Fitting/beast#468 is merged.

### CODE REVIEW

**Comment by lea-hagen** [comment]
I just did a manual rebase (it couldn't merge automatically after blackening in #41), so this can be merged once https://github.com/BEAST-Fitting/beast/pull/493 is merged.

**Comment by karllark** [comment]
Needs a minor update to the docs to remove the api build for beast_data.

**Comment by lea-hagen** [comment]
> Needs a minor update to the docs to remove the api build for beast_data.

Where do I make that change?  I haven't done anything with the api before, and I didn't find anything obvious in the code/docs.

**Comment by karllark** [comment]
It is at the end of the docs/index.rst file.

**Comment by lea-hagen** [comment]
Thanks!  Just removed it.

**Pull request merged**
