### PR TITLE
megabeast.py uses input file with settings

### PR DESCRIPTION
**Pull request by lea-hagen**
Instead of the filenames and assorted settings being in `megabeast.py`, it reads in a file with all of that info.  There's an example input file (using the METAL file structure), and documentation is updated.

### CODE REVIEW

**Comment by lea-hagen** [comment]
This also fixes the things I was puzzling about in #19.

**Comment by karllark** [comment]
Happy to merge this.  Just checking it is working and ready for merging.

**Comment by lea-hagen** [comment]
Yes, I ran though the whole thing with a METAL field and it worked great.  Though I'm not sure why so many of the checks are failing.

**Comment by karllark** [comment]
Checks are failing as we have *no* tests.  If one actual test was added, the checks should all be successful.  Something you might be willing to do?

**Comment by lea-hagen** [comment]
Ah, ok.  I've been thinking about tests, but I'll save that for a separate branch/pull request.

**Comment by karllark** [comment]
Yes, definitely.  I'll merge this pull request now.

**Pull request merged**
